backend:
  name: github
  repo: felixop8/my-personal-blog


media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    filter: {section: "projectPost"}
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'post' }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: projects
    label: Projects
    folder: content/projects
    create: true
    filter: {section: "projectPost"}
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'project' }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: github, label: GitHub}

